# This is a basic workflow that is manually triggered

name: Test Inputs workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      snpeversion:
        # Friendly description to be shown in the UI instead of 'name'
        description: '(1) SNPE-1.41.0 (2)SNPE-1.53.0'
        # Default value if no value is explicitly provided
        default: '1'
        # Input has to be provided for the workflow to run
        required: true
      imagetag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Target Docker image tag'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Set to use SNPE 1.41
      if: ${{ github.event.inputs.snpeversion == 1}}
      env: 
        snpever_string: snpe-1.41.0.zip
        
      run: echo "Hello ${{ env.snpever_string }}"
      
    - name: Set to use SNPE 1.53
      if: ${{ github.event.inputs.snpeversion == 2}}
      env: 
        snpever_string: snpe-1.53.0.zip
        
      run: echo "Hello ${{ env.snpever_string }}"

    - name: Show docker image tag
      run: echo "Docker Image tag':' ${{ github.event.inputs.imagetag }}"
      
