name: SNPE related push test workflow

on:
  push:
    paths:
      - "SNPE-Android-SDK-NDK/*"
      - "SNPE-Android-SDK-NDK/provisioning/*"
      - "SNPE-Android-SDK-NDK/utils/*"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: List all environment
      run: env 
