name: Test GCP
on:
  workflow_dispatch:
    # Inputs the workflow accepts
    inputs:
      snpeversion:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Select (1) SNPE-1.41.0, or (2)SNPE-1.53.0'
        # Default value if no value is explicitly provided
        default: '1'
        # Input has to be provided for the workflow to run
        required: true
      imagetag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Target Docker image tag'
        # Input has to be provided for the workflow to run
        required: true
  
jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:

      - name: Set to use SNPE 1.41
        if: ${{ github.event.inputs.snpeversion == 1}}
        env: 
          snpever_string: snpe-1.41.0.zip
        run: echo "SNPE Lib -  ${{ env.snpever_string }}"

      - name: Set to use SNPE 1.53
        if: ${{ github.event.inputs.snpeversion == 2}}
        env: 
          snpever_string: snpe-1.53.0.zip
        run: echo "SNPE Lib -  ${{ env.snpever_string }}"
        
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set GCS Security Token
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_SNPE_LIBS_READ }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Get snpe zip file'
        run: "cd SNPE-Android-SDK-NDK && gsutil cp gs://snpe-libs-for-docker/${{env.snpever_string}} snpe-lib.zip"
        
      - name: 'run ls'
        run: "cd SNPE-Android-SDK-NDK && ls -al"
        
      - name: 'build Docker image'
        run: "cd SNPE-Android-SDK-NDK && docker build -t snpe-build ."
        
      - name: 'Configure docker to use the gcloud command-line tool as a credential helper'
        run: "gcloud auth configure-docker -q"
      
      - name: 'tag image'
        run: "docker tag snpe-build gcr.io/${GCLOUD_PROJECT}/snpe-build:${{ github.event.inputs.imagetag }}"
        
      - name: 'push image to GCR'
        run: "docker push gcr.io/${GCLOUD_PROJECT}/snpe-build:${{ github.event.inputs.imagetag }}"
