name: Test GCP

on:
  workflow_dispatch
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set GCS Security Token
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_SNPE_LIBS_READ }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
      - name: 'Get snpe zip file'
        run: "gsutil cp gs://snpe-libs-for-docker/snpe-1.41.0.zip ."
        
      - name: 'run ls'
        run: "ls -al"
        
      - name: 'build Docker image'
        run: "docker build -t snpe-build-006 ."
        
      - name: 'Configure docker to use the gcloud command-line tool as a credential helper'
        run: "gcloud auth configure-docker -q"
      
      - name: 'tag image'
        run: "docker tag snpe-build-006 gcr.io/emc-et-gcr-d/snpe-build-006:snpe141build006"
        
      - name: 'push image to GCR'
        run: "docker push gcr.io/emc-et-gcr.d/snpe-build-006:snpe141build006"
